name: Build
on:
  push:
    branches:
      - dev
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GIT_TOKEN }}

      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GIT_TOKEN }}

      - uses: unfor19/install-aws-cli-action@master
      - name: AWS CLI Config
        run: |
          mkdir -p ~/.aws
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region ${{ secrets.AWS_DEFAULT_REGION }}
          aws ecr get-login-password --region ${{ secrets.AWS_DEFAULT_REGION }} | docker login --username AWS --password-stdin 953966107292.dkr.ecr.us-east-1.amazonaws.com

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          build-args: |
            GO_GIT_CRED__HTTPS__GITHUB__COM=${{ secrets.GO_GIT_CRED__HTTPS__GITHUB__COM}}
            GO_PRIVATE=${{ secrets.GO_PRIVATE }}
          push: true
          tags: 953966107292.dkr.ecr.us-east-1.amazonaws.com/uatizapi:latest
  
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:       
      - name: Create kube config
        run: |
          mkdir -p $HOME/.kube/
          mkdir -p ~/.aws
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region ${{ secrets.AWS_DEFAULT_REGION }}
          aws eks update-kubeconfig --region us-east-1 --name gateway-go

      - name: Checkout infra tools repo
        uses: actions/checkout@v3
        with:
          repository: marine-br/infrastructure
          token: ${{ secrets.GIT_TOKEN }}
          path: 
      - name: Install helm
        run: |
          curl -LO https://get.helm.sh/helm-v3.8.0-linux-amd64.tar.gz
          tar -zxvf helm-v3.8.0-linux-amd64.tar.gz
          mv linux-amd64/helm /usr/local/bin/helm
          helm version
      - name: Lint helm charts
        run: helm lint ./helm-packages/apps/whatsapp-api
      
      - uses: unfor19/install-aws-cli-action@master
      - name: AWS CLI Config
        run: |
          mkdir -p ~/.aws
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region ${{ secrets.AWS_DEFAULT_REGION }}
      - name: Deploy
        run: |
          helm upgrade --install whatsapp-api-uatizapi ./helm-packages/apps/whatsapp-api -f ./helm-packages/apps/whatsapp-api/values.yaml \
            --namespace gateway-prod --create-namespace \
            --set image.tag=latest
