name: Build
on:
    push:
        branches:
            - main
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  token: ${{ secrets.GIT_TOKEN }}

            - uses: digitalocean/action-doctl@v2
              with:
                  token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

            - name: Log in to DigitalOcean Container Registry with short-lived credentials
              run: doctl registry login --expiry-seconds 1200

            - name: Build and push
              uses: docker/build-push-action@v2
              with:
                  context: .
                  build-args: |
                      GO_GIT_CRED__HTTPS__GITHUB__COM=${{ secrets.GO_GIT_CRED__HTTPS__GITHUB__COM}}
                      GO_PRIVATE=${{ secrets.GO_PRIVATE }}
                  push: true
                  tags: registry.digitalocean.com/marine-repo/whatsapp-api:latest

    deploy:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Create kube config
              run: |
                  mkdir -p $HOME/.kube/
                  echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config
                  chmod 600 $HOME/.kube/config

            - name: Checkout infra tools repo
              uses: actions/checkout@v3
              with:
                  repository: marine-br/infrastructure
                  token: ${{ secrets.GIT_TOKEN }}
                  path:
            - name: Install helm
              run: |
                  curl -LO https://get.helm.sh/helm-v3.8.0-linux-amd64.tar.gz
                  tar -zxvf helm-v3.8.0-linux-amd64.tar.gz
                  mv linux-amd64/helm /usr/local/bin/helm
                  helm version
            - name: Lint helm charts
              run: helm lint ./helm-packages/apps/whatsapp-api
            - name: Deploy
              run: |
                  helm upgrade --install --recreate-pods whatsapp-api ./helm-packages/apps/whatsapp-api -f ./helm-packages/apps/whatsapp-api/values.yaml \
                    --namespace gateway-prod --create-namespace \
                    --set image.tag=latest
